name: Playwright Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  playwright:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright/java:v1.44.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests
        run: ./run_tests.sh

